localhub/private_messages/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Localhub
from localhub.users.urls import user_re_path

# Local
from . import views

app_name = "private_messages"

urlpatterns = [
    path("inbox/", views.inbox_view, name="inbox"),
    path("outbox/", views.outbox_view, name="outbox"),
    path("send/", views.message_create_view, name="message_create"),
    path("~/mark-read/", views.message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", views.message_detail_view, name="message_detail"),
    path("message/<int:pk>/~reply/", views.message_reply_view, name="message_reply"),
    path(
        "message/<int:pk>/~follow-up/",
        views.message_reply_view,
        name="message_follow_up",
        kwargs={"is_follow_up": True},
    ),
    path("message/<int:pk>/~delete/", views.message_delete_view, name="message_delete"),
    path(
        "message/<int:pk>/~read/",
        views.message_mark_read_view,
        name="message_mark_read",
    ),
    path(
        "message/<int:pk>/~bookmark/",
        views.message_bookmark_view,
        name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        views.message_bookmark_view,
        name="message_remove_bookmark",
        kwargs={
            "remove": True,
        },
    ),
    user_re_path(
        r"~send/$",
        views.message_recipient_create_view,
        name="message_create_recipient",
    ),
]

localhub/tags/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from . import views

app_name = "activities"

urlpatterns = [
    path("", views.tag_list_view, name="tag_list"),
    path("following/", views.following_tag_list_view, name="following_tag_list",),
    path("blocked/", views.blocked_tag_list_view, name="blocked_tag_list"),
    path(
        "autocomplete/", views.tag_autocomplete_list_view, name="tag_autocomplete_list",
    ),
    path("<int:pk>/~follow/", views.tag_follow_view, name="tag_follow"),
    path("<int:pk>/~unfollow/", views.tag_unfollow_view, name="tag_unfollow",),
    path("<int:pk>/~block/", views.tag_block_view, name="tag_block"),
    path("<int:pk>/~unblock/", views.tag_unblock_view, name="tag_unblock"),
    path("<slug:slug>/", views.tag_detail_view, name="tag_detail"),
]

localhub/users/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path, re_path

# Local
from . import views

app_name = "users"

USERNAME_RE = r"^(?P<username>[\w.@+-]+)/"


def user_re_path(path, *args, **kwargs):
    return re_path(USERNAME_RE + path, *args, **kwargs)


urlpatterns = [
    path("autocomplete/", views.user_autocomplete_list_view, name="autocomplete_list"),
    path("members/", views.member_list_view, name="member_list"),
    path("following/", views.following_user_list_view, name="following_list"),
    path("followers/", views.follower_user_list_view, name="follower_list"),
    path("blocked/", views.blocked_user_list_view, name="blocked_list"),
    user_re_path(r"likes/$", views.user_activity_likes_view, name="activity_likes"),
    user_re_path(
        r"likes/comments/$",
        views.user_comment_likes_view,
        name="comment_likes",
    ),
    user_re_path(
        r"mentions/$",
        views.user_activity_mentions_view,
        name="activity_mentions",
    ),
    user_re_path(
        r"mentions/comments/$",
        views.user_comment_mentions_view,
        name="comment_mentions",
    ),
    user_re_path(r"follow/$", views.user_follow_view, name="follow"),
    user_re_path(
        r"unfollow/$", views.user_follow_view, name="unfollow", kwargs={"remove": True}
    ),
    user_re_path(r"block/$", views.user_block_view, name="block"),
    user_re_path(
        r"unblock/$", views.user_block_view, name="unblock", kwargs={"remove": True}
    ),
    user_re_path(r"comments/$", views.user_comment_list_view, name="comments"),
    user_re_path(r"messages/$", views.user_message_list_view, name="messages"),
    user_re_path(r"$", views.user_stream_view, name="activities"),
]

localhub/apps/events/views/list.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

import calendar
import datetime

from django.http import Http404
from django.utils import timezone
from django.utils.functional import cached_property
from django.views.generic.dates import DateMixin, DayMixin, MonthMixin, YearMixin

import pytz

from localhub.apps.activities.views.list_detail import (
    ActivityListView,
    BaseActivityListView,
)

from ..models import Event


class EventListView(ActivityListView):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_relevance()
            .with_timedelta()
            .order_by("-relevance", "timedelta")
        )


class EventCalendarView(
    YearMixin, MonthMixin, DayMixin, DateMixin, BaseActivityListView
):
    template_name = "events/calendar.html"
    date_field = "starts"
    paginate_by = None
    allow_future = True
    model = Event

    def get_allow_empty(self):
        # empty month view is fine, but you should not be able
        # to navigate to a single date missing any events.
        return not (self.current_day)

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Event.InvalidDate:
            raise Http404("These dates are not valid")

    @cached_property
    def current_day(self):
        try:
            return int(self.get_day())
        except (Http404, ValueError):
            return None

    @cached_property
    def current_month(self):
        try:
            return int(self.get_month())
        except (Http404, ValueError):
            return timezone.now().month

    @cached_property
    def current_year(self):
        try:
            return int(self.get_year())
        except (Http404, ValueError):
            return timezone.now().year

    def get_queryset(self):
        # for rep
        qs = (
            super()
            .get_queryset()
            .published_or_owner(self.request.user)
            .with_next_date()
            .exclude_blocked(self.request.user)
            .filter(parent__isnull=True)
            .order_by("next_date")
        )
        if self.current_day:
            qs = qs.for_date(self.current_day, self.current_month, self.current_year)
        else:
            qs = qs.for_month(self.current_month, self.current_year)
        return qs

    def make_date(self, day):
        try:
            return datetime.date(
                day=day, month=self.current_month, year=self.current_year,
            )
        except ValueError:
            raise Event.InvalidDate()

    def make_datetime(self, day):
        try:
            return datetime.datetime(
                day=day,
                month=self.current_month,
                year=self.current_year,
                tzinfo=pytz.UTC,
            )
        except ValueError:
            raise Event.InvalidDate()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        if self.current_day:
            data["current_date"] = self.make_date(self.current_day)
            match_datetime = self.make_datetime(self.current_day)
            data["events"] = [
                event
                for event in self.object_list
                if event.matches_date(match_datetime)
            ]
            return data

        now = timezone.now()

        data["current_month"] = first_of_month = self.make_date(1)

        data.update(
            {
                "next_month": self.get_next_month(first_of_month),
                "previous_month": self.get_previous_month(first_of_month),
                "slots": self.get_slots(),
                "today": now,
                "is_today": now.month == first_of_month.month
                and now.year == first_of_month.year,
            }
        )

        return data

    def get_slots(self):
        """Group events by day into tuples of (number, events)
        """

        return [
            (
                day,
                is_past,
                [event for event in self.object_list if dt and event.matches_date(dt)],
            )
            for day, is_past, dt in self.iter_dates()
        ]

    def is_past(self, day):
        now = timezone.now()
        # any month in the future
        if self.current_month > now.month and self.current_year >= now.year:
            return False

        # any month in the past
        if self.current_month < now.month:
            return True

        # this month
        return now.day > day

    def iter_dates(self):
        """Yields tuple of (counter, is_past, datetime) for each day of month. If day
        falls out of range yields zero, False, None.
        """
        try:
            for day in calendar.Calendar().itermonthdays(
                self.current_year, self.current_month
            ):
                if day > 0:
                    yield day, self.is_past(day), self.make_datetime(day=day)
                else:
                    # falls outside the day range
                    yield 0, False, None
        except ValueError:
            raise Event.InvalidDate()


event_calendar_view = EventCalendarView.as_view()

localhub/communities/views/base.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class CommunityRequiredMixin(LoginRequiredMixin):
    """
    Ensures that a community is available on this domain. This requires
    the CurrentCommunityMiddleware is enabled.

    If the user is not a member they will be redirected to the Welcome view.

    If the view has the `allow_non_members` property *True* then the above
    rule is overriden - for example in some cases where we want to allow
    the user to be able to handle an invitation.
    """

    allow_non_members = False

    def dispatch(self, request, *args, **kwargs):
        if not request.community.active:
            return self.handle_community_not_found()

        if (
            request.user.is_authenticated
            and not request.user.has_perm(
                "communities.view_community", request.community
            )
            and not self.allow_non_members
        ):
            return self.handle_community_access_denied()
        return super().dispatch(request, *args, **kwargs)

    def handle_community_access_denied(self):
        if self.request.is_ajax():
            raise PermissionDenied(_("You must be a member of this community"))
        return HttpResponseRedirect(reverse("community_welcome"))

    def handle_community_not_found(self):
        if self.request.is_ajax():
            raise Http404(_("No community is available for this domain"))
        return HttpResponseRedirect(reverse("community_not_found"))

localhub/hashtags/views/list.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


from django.conf import settings
from django.db.models import BooleanField, Count, Exists, OuterRef, Q, Value
from django.views.generic import ListView

from taggit.models import Tag

from localhub.views import SearchMixin

from .mixins import TagQuerySetMixin


class BaseTagListView(TagQuerySetMixin, ListView):
    def get_queryset(self):
        return super().get_queryset().order_by("name")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["content_warnings"] = [
            tag.strip().lower()[1:]
            for tag in self.request.community.content_warning_tags.split()
        ]
        return data


class TagAutocompleteListView(BaseTagListView):
    template_name = "hashtags/tag_autocomplete_list.html"
    exclude_unused_tags = True

    def get_queryset(self):
        search_term = self.request.GET.get("q", "").strip()
        if not search_term:
            return Tag.objects.none()
        return super().get_queryset().filter(name__istartswith=search_term)


tag_autocomplete_list_view = TagAutocompleteListView.as_view()


class TagListView(SearchMixin, BaseTagListView):
    template_name = "hashtags/tag_list.html"
    paginate_by = settings.LOCALHUB_LONG_PAGE_SIZE
    exclude_unused_tags = True

    def get_queryset(self):

        qs = super().get_queryset()

        if self.search_query:
            qs = qs.filter(name__icontains=self.search_query)

        if self.request.user.is_authenticated:
            qs = qs.annotate(
                is_following=Exists(
                    self.request.user.following_tags.filter(pk=OuterRef("id"))
                )
            )
        else:
            qs = qs.annotate(is_following=Value(False, BooleanField()))

        qs = qs.annotate(
            item_count=Count(
                "taggit_taggeditem_items",
                filter=Q(taggit_taggeditem_items__pk__in=self.get_tagged_items()),
            )
        )

        return qs.order_by("-item_count", "name")


tag_list_view = TagListView.as_view()


class FollowingTagListView(BaseTagListView):
    template_name = "hashtags/following_tag_list.html"

    def get_queryset(self):
        return self.request.user.following_tags.order_by("name")


following_tag_list_view = FollowingTagListView.as_view()


class BlockedTagListView(BaseTagListView):
    template_name = "hashtags/blocked_tag_list.html"

    def get_queryset(self):
        return self.request.user.blocked_tags.order_by("name")


blocked_tag_list_view = BlockedTagListView.as_view()

localhub/private_messages/views/list.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.db.models import F
from django.views.generic import ListView

from localhub.views import SearchMixin

from .mixins import RecipientQuerySetMixin, SenderQuerySetMixin


class BaseMessageListView(SearchMixin, ListView):
    paginate_by = settings.LOCALHUB_DEFAULT_PAGE_SIZE


class InboxView(RecipientQuerySetMixin, BaseMessageListView):
    """
    Messages received by current user
    oere we should show the sender, timestamp...
    """

    template_name = "private_messages/inbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by(F("read").desc(nulls_first=True), "-created")


inbox_view = InboxView.as_view()


class OutboxView(SenderQuerySetMixin, BaseMessageListView):
    """
    Messages sent by current user
    """

    template_name = "private_messages/outbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by("-created")


outbox_view = OutboxView.as_view()

localhub/users/views/edit.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.utils.translation import gettext_lazy as _

from rules.contrib.views import PermissionRequiredMixin

from localhub.views import SuccessUpdateView

from ..forms import UserForm
from .mixins import CurrentUserMixin


class UserUpdateView(
    CurrentUserMixin, PermissionRequiredMixin, SuccessUpdateView,
):
    permission_required = "users.change_user"
    success_message = _("Your details have been updated")
    form_class = UserForm
    template_name = "users/user_form.html"

    def get_success_url(self):
        return self.request.path

    def form_valid(self, form):
        self.object = form.save()
        self.object.notify_on_update()
        return self.success_response()


user_update_view = UserUpdateView.as_view()

localhub/users/views/form.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.utils.translation import gettext_lazy as _
from rules.contrib.views import PermissionRequiredMixin

from localhub.views import SuccessUpdateView

from ..forms import UserForm
from .mixins import CurrentUserMixin


class UserUpdateView(
    CurrentUserMixin, PermissionRequiredMixin, SuccessUpdateView,
):
    permission_required = "users.change_user"
    success_message = _("Your details have been updated")
    form_class = UserForm
    template_name = "users/user_form.html"

    def get_success_url(self):
        return self.request.path

    def form_valid(self, form):
        self.object = form.save()
        self.object.notify_on_update()
        return self.success_response()


user_update_view = UserUpdateView.as_view()

templates/users/list/autocomplete.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load users %}

{% for user_obj in users %}
<li class="cursor-pointer p-1 hover:bg-gray-500 hover:text-white {% if forloop.first %} bg-gray-500 text-white selected{% endif %}"
    data-action="click->typeahead#select"
    data-typeahead-value="{{ user_obj.username }}"
    data-typeahead-key="@">
  <div class="flex items-center">
    <span class="inline-block">
      @{{ user_obj.username }}
    </span>
  </div>
</li>
{% endfor %}

templates/users/list/base.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "base.html" %}
{% load i18n rules %}

{% block subtitle %} / {% trans "People" %}{% endblock %}

{% block content %}

{% test_rule "communities.is_member" user community as is_member %}

{% has_perm "private_messages.create_message" user community as can_create_message %}

<h1 class="page-header mb-3">{% trans "People" %}</h1>

{% if is_member %}
<div class="tabs mb-3 text-sm">
  {% active_link 'users:member_list' as link %}
  <a class="tab-item{% if link.match %} active{% endif %}"
     href="{{ link.url }}">{% trans "Members" %}</a>
  {% active_link 'users:following_list' as link %}
  <a class="tab-item{% if link.match %} active{% endif %}"
     href="{{ link.url }}">{% trans "Following" %}</a>
  {% active_link 'users:follower_list' as link %}
  <a class="tab-item{% if link.match %} active{% endif %}"
     href="{{ link.url }}">{% trans "Followers" %}</a>
  {% active_link 'users:blocked_list' as link %}
  <a class="tab-item{% if link.match %} active{% endif %}"
     href="{{ link.url }}">{% trans "Blocked" %}</a>
</div>
{% endif %}

{% block user_list %}


{% if object_list %}

{% block counter_container %}
<div class="notification font-bold mb-3">
  {% block counter %}
  {% endblock counter %}
</div>
{% endblock counter_container %}

{% if page_obj.number > 1 %}
{% include "includes/pagination.html" with css_class="mb-3" %}
{% endif %}

<table class="table-auto-scroll text-sm bg-white">
  <tbody>
    {% for object in object_list %}
    <tr class="{% cycle '' 'bg-gray-100' %} hover:bg-gray-200">
      <td class="border-t border-l border-b py-2 px-2 w-3/4">
        <div class="flex flex-wrap items-center">

          {% block user_item_detail %}
          {% if object.num_unread_messages %}
          {% url 'users:messages' object.username as messages_url %}
          {% include "users/includes/chip.html" with profile=object profile_url=messages_url css_class="mr-2" %}
          {% else %}
          {% include "users/includes/chip.html" with profile=object css_class="mr-2" %}
          {% endif %}

          {% if object.role == "admin" or object.role == "moderator" %}
          <span class="tag px-1 mr-2">{{ object.role_display }}</span>
          {% endif %}

          {% if object.num_unread_messages %}
          <span class="tag px-1">{% trans "New" %}</span>
          {% endif %}
          {% endblock user_item_detail %}
      </td>
      {% if is_member %}
      <td class="border py-2 px-2">
        <div class="table-nav">
          {% block user_item_actions %}
          {% if user == object %}
          <a class="table-nav-item"
             href="{% url 'user_update' %}">{% trans "Settings" %}</a>
          {% else %}
          {% has_perm "users.follow_user" user object as can_follow_user %}
          {% if can_follow_user %}
          <div class="table-nav-item">
            <turbo-frame id="user-{{ object.id }}-follow">
              {% include "users/includes/follow.html" with is_following=object.is_following %}
            </turbo-frame>
          </div>
          {% endif %}

          {% if can_create_message %}
          <a class="table-nav-item"
             href="{% url 'private_messages:message_create_recipient' object.username %}"
             data-turbo-frame="modal">
            {% trans "Send Message" %}
          </a>
          {% endif %}
          {% endif %}
        </div>
        {% endblock user_item_actions %}
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}
{% endblock user_list %}
{% endblock content %}

templates/users/list/blocked.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Blocked" %}{% endblock %}

{% block counter %}
{% blocktrans count counter=paginator.count %}
You have blocked one person.
{% plural %}
You have blocked {{ counter }} people.
{% endblocktrans %}
{% endblock counter %}

{% block user_item_actions %}
<div class="table-nav">
  <a class="table-nav-item line-through"
     href="{% url 'users:unblock' object.username %}"
     role="button"
     data-turbo="false"
     data-controller="ajax"
     data-action="ajax#post toggle#toggle"
     data-ajax-redirect-value="{{ request.get_full_path }}">
    {% trans "Block" %}
  </a>
</div>
{% endblock %}

templates/users/list/followers.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Followers" %}{% endblock %}

{% block counter %}
{% blocktrans count counter=paginator.count %}
You have one follower.
{% plural %}
You have {{ counter }} followers.
{% endblocktrans %}
{% endblock counter %}

templates/users/list/following.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Following" %}{% endblock %}

{% block counter %}
{% blocktrans count counter=paginator.count %}
You are following one person.
{% plural %}
You are following {{ counter }} people.
{% endblocktrans %}
{% endblock counter %}

templates/users/list/members.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "users/list/base.html" %}
{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Members" %}{% endblock %}

{% block counter_container %}
{% if not view.search_query %}
{{ block.super }}
{% endif %}
{% endblock counter_container %}


{% block counter %}
{% blocktrans count counter=paginator.count %}
This site has one member.
{% plural %}
This site has {{ counter }} members.
{% endblocktrans %}
{% endblock counter %}

{% block user_list %}
<div class="mb-1">
  {% include "includes/forms/search_form.html" with selector=True %}
</div>
{{ block.super }}
{% endblock user_list %}