localhub/bookmarks/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from .views import (
    bookmarks_comment_list_view,
    bookmarks_message_list_view,
    bookmarks_stream_view,
)

app_name = "bookmarks"

urlpatterns = [
    path("", bookmarks_stream_view, name="activities"),
    path("comments/", bookmarks_comment_list_view, name="comments"),
    path("messages/", bookmarks_message_list_view, name="messages"),
]

localhub/notifications/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from . import views

app_name = "notifications"

urlpatterns = [
    path("", views.notification_list_view, name="list"),
    path("service-worker.js", views.service_worker_view, name="service_worker"),
    path("~subscribe/", views.subscribe_view, name="subscribe"),
    path(
        "~unsubscribe/",
        views.subscribe_view,
        name="unsubscribe",
        kwargs={"remove": True},
    ),
    path("<int:pk>/~delete/", views.notification_delete_view, name="delete"),
    path("<int:pk>/~mark-read/", views.notification_mark_read_view, name="mark_read"),
    path("~delete-all/", views.notification_delete_all_view, name="delete_all"),
    path(
        "~mark-all-read/",
        views.notification_mark_all_read_view,
        name="mark_all_read",
    ),
]

localhub/private_messages/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Localhub
from localhub.users.urls import user_re_path

# Local
from . import views

app_name = "private_messages"

urlpatterns = [
    path("inbox/", views.inbox_view, name="inbox"),
    path("outbox/", views.outbox_view, name="outbox"),
    path("send/", views.message_create_view, name="message_create"),
    path("~/mark-read/", views.message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", views.message_detail_view, name="message_detail"),
    path("message/<int:pk>/~reply/", views.message_reply_view, name="message_reply"),
    path(
        "message/<int:pk>/~follow-up/",
        views.message_reply_view,
        name="message_follow_up",
        kwargs={"is_follow_up": True},
    ),
    path("message/<int:pk>/~delete/", views.message_delete_view, name="message_delete"),
    path(
        "message/<int:pk>/~read/",
        views.message_mark_read_view,
        name="message_mark_read",
    ),
    path(
        "message/<int:pk>/~bookmark/",
        views.message_bookmark_view,
        name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        views.message_bookmark_view,
        name="message_remove_bookmark",
        kwargs={
            "remove": True,
        },
    ),
    user_re_path(
        r"~send/$",
        views.message_recipient_create_view,
        name="message_create_recipient",
    ),
]

localhub/tags/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from . import views

app_name = "activities"

urlpatterns = [
    path("", views.tag_list_view, name="tag_list"),
    path("following/", views.following_tag_list_view, name="following_tag_list",),
    path("blocked/", views.blocked_tag_list_view, name="blocked_tag_list"),
    path(
        "autocomplete/", views.tag_autocomplete_list_view, name="tag_autocomplete_list",
    ),
    path("<int:pk>/~follow/", views.tag_follow_view, name="tag_follow"),
    path("<int:pk>/~unfollow/", views.tag_unfollow_view, name="tag_unfollow",),
    path("<int:pk>/~block/", views.tag_block_view, name="tag_block"),
    path("<int:pk>/~unblock/", views.tag_unblock_view, name="tag_unblock"),
    path("<slug:slug>/", views.tag_detail_view, name="tag_detail"),
]

localhub/bookmarks/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.contrib.auth.decorators import login_required

# Localhub
from localhub.activities.views.streams import render_activity_stream
from localhub.comments.models import Comment
from localhub.common.pagination import render_paginated_queryset
from localhub.communities.decorators import community_required
from localhub.private_messages.models import Message


@login_required
@community_required
def bookmarks_stream_view(request):
    def _filter_queryset(qs):
        qs = (
            qs.published_or_owner(request.user)
            .bookmarked(request.user)
            .with_bookmarked_timestamp(request.user)
        )

        if request.search:
            qs = qs.search(qs)
        return qs

    return render_activity_stream(
        request,
        _filter_queryset,
        "bookmarks/activities.html",
        ordering=("-rank", "-bookmarked")
        if request.search
        else ("-bookmarked", "-created"),
    )


@login_required
@community_required
def bookmarks_message_list_view(request):
    messages = (
        Message.objects.for_community(request.community)
        .for_sender_or_recipient(request.user)
        .common_select_related()
        .bookmarked(request.user)
        .with_bookmarked_timestamp(request.user)
        .distinct()
    )

    if request.search:
        messages = messages.search(request.search)
        ordering = ("-rank", "-bookmarked")
    else:
        ordering = ("-bookmarked", "-created")

    messages = messages.order_by(*ordering)

    return render_paginated_queryset(
        request,
        messages,
        "bookmarks/messages.html",
    )


@login_required
@community_required
def bookmarks_comment_list_view(request):
    comments = (
        Comment.objects.for_community(request.community)
        .with_common_annotations(request.user, request.community)
        .exclude_blocked_users(request.user)
        .exclude_deleted()
        .with_common_related()
        .bookmarked(request.user)
        .with_bookmarked_timestamp(request.user)
    )
    if request.search:
        comments = comments.search(request.search)
        ordering = ("-rank", "-bookmarked")
    else:
        ordering = ("-bookmarked", "-created")

    comments = comments.order_by(*ordering)

    return render_paginated_queryset(request, comments, "bookmarks/comments.html")

localhub/notifications/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Standard Library
import http
import json

# Django
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST

# Third Party Libraries
from turbo_response import TurboStream

# Localhub
from localhub.common.pagination import render_paginated_queryset
from localhub.communities.decorators import community_required

# Local
from .models import Notification, PushSubscription
from .signals import notification_read


@login_required
@community_required
def notification_list_view(request):
    qs = (
        get_notification_queryset(request)
        .exclude_blocked_actors(request.user)
        .prefetch_related("content_object")
        .select_related("actor", "content_type", "community", "recipient")
        .order_by("is_read", "-created")
    )

    return render_paginated_queryset(
        request,
        qs,
        "notifications/notification_list.html",
        {
            "is_unread_notifications": qs.filter(is_read=False).exists(),
            "webpush_settings": {
                "public_key": settings.VAPID_PUBLIC_KEY,
                "enabled": settings.WEBPUSH_ENABLED,
            },
        },
        page_size=settings.LONG_PAGE_SIZE,
    )


@require_POST
@login_required
@community_required
def notification_mark_all_read_view(request):
    qs = get_unread_notification_queryset(request)
    [
        notification_read.send(
            sender=notification.content_object.__class__,
            instance=notification.content_object,
        )
        for notification in qs.prefetch_related("content_object")
    ]
    qs.update(is_read=True)
    return redirect("notifications:list")


@require_POST
@login_required
@community_required
def notification_mark_read_view(request, pk):
    obj = get_object_or_404(get_unread_notification_queryset(request), pk=pk)
    obj.is_read = True
    obj.save()
    notification_read.send(
        sender=obj.content_object.__class__,
        instance=obj.content_object,
    )

    target = (
        f"notification-{obj.id}"
        if Notification.objects.filter(recipient=request.user, is_read=False).exists()
        else "notifications"
    )
    return TurboStream(target).remove.response()


@require_POST
@login_required
@community_required
def notification_delete_all_view(request):
    get_notification_queryset(request).delete()
    return redirect("notifications:list")


@require_POST
@login_required
@community_required
def notification_delete_view(request, pk):
    obj = get_object_or_404(get_notification_queryset(request), pk=pk)
    target = f"notification-{obj.id}"
    obj.delete()
    return TurboStream(target).remove.response()


@require_POST
@login_required
@community_required
def subscribe_view(request, remove=False):

    try:
        json_body = json.loads(request.body.decode("utf-8"))

        data = {"endpoint": json_body["endpoint"]}
        keys = json_body["keys"]
        data["auth"] = keys["auth"]
        data["p256dh"] = keys["p256dh"]

    except (ValueError, KeyError):
        return HttpResponseBadRequest()

    data |= {"user": request.user, "community": request.community}

    if remove:
        PushSubscription.objects.filter(**data).delete()
        status = http.HTTPStatus.OK
    else:
        try:
            _, created = PushSubscription.objects.get_or_create(**data)
            status = http.HTTPStatus.CREATED if created else http.HTTPStatus.OK
        except IntegrityError:
            pass  # dupe, ignore
    return JsonResponse({"message": "ok"}, status=status)


def service_worker_view(request):
    """
    Returns template containing serviceWorker JS, can't use
    static as must always be under domain. We can also pass
    in server specific settings.
    """

    return TemplateResponse(
        request,
        "notifications/service_worker.js",
        {"vapid_public_key": settings.VAPID_PUBLIC_KEY},
        content_type="application/javascript",
    )


def get_notification_queryset(request):
    return Notification.objects.for_community(request.community).filter(
        recipient=request.user
    )


def get_unread_notification_queryset(request):
    return get_notification_queryset(request).filter(is_read=False)

localhub/private_messages/views/edit.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


from django.contrib.auth import get_user_model
from django.utils.functional import cached_property
from django.utils.translation import gettext as _

from rules.contrib.views import PermissionRequiredMixin

from localhub.communities.views import CommunityRequiredMixin
from localhub.views import ParentObjectMixin, SuccessFormView

from ..forms import MessageForm, MessageRecipientForm
from .mixins import RecipientQuerySetMixin, SenderQuerySetMixin


class BaseMessageFormView(PermissionRequiredMixin, SuccessFormView):

    permission_required = "private_messages.create_message"
    template_name = "private_messages/message_form.html"
    form_class = MessageForm

    def get_permission_object(self):
        return self.request.community

    def get_success_message(self):
        return _("Your message has been sent to %(recipient)s") % {
            "recipient": self.object.recipient.get_display_name()
        }


class BaseReplyFormView(ParentObjectMixin, BaseMessageFormView):
    @cached_property
    def recipient(self):
        return self.parent.get_other_user(self.request.user)

    def get_parent_queryset(self):
        return self.get_queryset()

    def notify(self):
        """Handle any notifications to recipient here"""
        ...

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.community = self.request.community
        self.object.sender = self.request.user
        self.object.recipient = self.recipient
        self.object.parent = self.parent
        self.object.save()

        self.notify()

        return self.success_response()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["recipient"] = self.recipient
        return data


class MessageReplyView(RecipientQuerySetMixin, BaseReplyFormView):
    def notify(self):
        self.object.notify_on_reply()

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form["message"].label = _(
            "Send reply to %(recipient)s"
            % {"recipient": self.recipient.get_display_name()}
        )
        return form


message_reply_view = MessageReplyView.as_view()


class MessageFollowUpView(SenderQuerySetMixin, BaseReplyFormView):
    def notify(self):
        self.object.notify_on_follow_up()

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form["message"].label = _(
            "Send follow-up to %(recipient)s"
            % {"recipient": self.recipient.get_display_name()}
        )
        return form


message_follow_up_view = MessageFollowUpView.as_view()


class MessageRecipientCreateView(
    CommunityRequiredMixin, ParentObjectMixin, BaseMessageFormView,
):
    """Send new message to a specific recipient"""

    parent_object_name = "recipient"
    parent_slug_kwarg = "username"
    parent_slug_field = "username"

    def get_parent_queryset(self):
        return (
            get_user_model()
            .objects.exclude(pk=self.request.user.id)
            .for_community(self.request.community)
            .exclude_blocking(self.request.user)
        )

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form["message"].label = _(
            "Send message to %(recipient)s"
            % {"recipient": self.recipient.get_display_name()}
        )
        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.community = self.request.community
        self.object.sender = self.request.user
        self.object.recipient = self.recipient
        self.object.save()

        self.object.notify_on_send()

        return self.success_response()


message_recipient_create_view = MessageRecipientCreateView.as_view()


class MessageCreateView(
    CommunityRequiredMixin, BaseMessageFormView,
):
    """
    Send message to any individual recipient
    """

    form_class = MessageRecipientForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.community = self.request.community
        self.object.sender = self.request.user
        self.object.save()

        self.object.notify_on_send()

        return self.success_response()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs.update(
            {"community": self.request.community, "sender": self.request.user}
        )

        return kwargs


message_create_view = MessageCreateView.as_view()

localhub/private_messages/views/list.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.db.models import F
from django.views.generic import ListView

from localhub.views import SearchMixin

from .mixins import RecipientQuerySetMixin, SenderQuerySetMixin


class BaseMessageListView(SearchMixin, ListView):
    paginate_by = settings.LOCALHUB_DEFAULT_PAGE_SIZE


class InboxView(RecipientQuerySetMixin, BaseMessageListView):
    """
    Messages received by current user
    oere we should show the sender, timestamp...
    """

    template_name = "private_messages/inbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by(F("read").desc(nulls_first=True), "-created")


inbox_view = InboxView.as_view()


class OutboxView(SenderQuerySetMixin, BaseMessageListView):
    """
    Messages sent by current user
    """

    template_name = "private_messages/outbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by("-created")


outbox_view = OutboxView.as_view()

templates/private_messages/includes/bookmark.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
<form method="post"
      action="{% if has_bookmarked %}{% url 'private_messages:message_remove_bookmark' object.id %}{% else %}{% url 'private_messages:message_bookmark' object.id %}{% endif %}">
  {% csrf_token %}
  {% if has_bookmarked %}
  <button class="dropdown-menu-item line-through">{% trans "Bookmark" %}</button>
  {% else %}
  <button class="dropdown-menu-item">{% trans "Bookmark" %}</button>
  {% endif %}
</form>

templates/private_messages/includes/email_settings.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load users %}

{% dismissable user "messages-emails" %}
{% url 'user_update' as user_settings_url %}
{% blocktrans %}
You can enable email notifications for new messages <a href="{{ user_settings_url }}">in your settings</a>.
{% endblocktrans %}
{% enddismissable %}

templates/private_messages/includes/message.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load account %}
{% load users %}

<div class="card {{ css_class|default:"mb-3" }}"
     id="message-{{ message.id }}"
     data-controller="clipboard"
     data-clipboard-message-value="{% trans 'Markdown content has been copied' %}">

  <div class="flex flex-wrap items-center text-sm mb-3">
    {% include "users/includes/chip.html" with profile=message.sender profile_url=sender_url css_class="mr-2" %}
    <div class="mr-2 text-muted">
      {% trans "to" %}
    </div>
    {% include "users/includes/chip.html" with profile=message.recipient profile_url=recipient_url css_class="mr-2" %}
    <span class="mr-2 text-muted">
      {% blocktrans with created=message.created|timesince %}
      {{ created }} ago
      {% endblocktrans %}
    </span>
    {% if is_unread %}
    <div class="tag tag-primary">{% trans "New" %}</div>
    {% endif %}
  </div>

  {% collapsable is_detail %}
  <div class="markdown-content mb-3">
    {{ message.message.markdown|strip_external_images:user|lazify }}
  </div>
  {% endcollapsable %}
  <textarea data-clipboard-target="textarea"
            readonly
            class="hidden">{{ message.message }}</textarea>

  <div class="card-footer">
    <div class="flex flex-wrap items-center">
      <div class="mr-2 text-sm"
           data-controller="dropdown"
           data-action="click@window->dropdown#close keydown@window->dropdown#close">
        <button class="btn btn-dropdown"
                data-action="dropdown#toggle">
          {% trans "Actions..." %}
        </button>

        <div class="dropdown-menu hidden mt-1"
             data-dropdown-target="menu">

          {% if is_recipient and not message.read %}
          <form id="message-{{ message.id }}-mark-read"
                method="post"
                action="{% url 'private_messages:message_mark_read' message.id %}">
            {% csrf_token %}
            <button class="dropdown-menu-item">{% trans "Mark As Read" %}</button>
          </form>
          {% endif %}
          <turbo-frame id="message-{{ message.id }}-bookmark">
            {% include "private_messages/includes/bookmark.html" with object=message has_bookmarked=message.has_bookmarked %}
          </turbo-frame>

          {% if can_reply %}
          <a href="{% url 'private_messages:message_reply' message.id %}"
             class="dropdown-menu-item">
            {% trans "Reply" %}
          </a>
          {% elif can_follow_up %}
          <a href="{% url 'private_messages:message_follow_up' message.id %}"
             class="dropdown-menu-item">
            {% trans "Follow-Up" %}
          </a>
          {% endif %}
          <form method="post"
                action="{% url 'private_messages:message_delete' message.id %}"
                data-controller="confirm"
                data-action="confirm#confirm"
                data-confirm-text-value="{% trans "Are you sure you want to delete this message? Replies to this message will not be deleted. The message may still be available to the other person." %}">
            {% csrf_token %}
            {% if is_detail %}
            <input type="hidden"
                   name="redirect"
                   value="true">
            {% endif %}
            <button class="dropdown-menu-item">
              {% trans "Delete" %}
            </button>
          </form>
          <a href="#"
             class="dropdown-menu-item"
             role="button"
             data-turbo="false"
             data-clipboard-target="button"
             data-action="clipboard#copy">
            {% trans "Copy Markdown" %}
          </a>
        </div>

      </div>
      {% if not is_detail %}
      <a class="inline-block mr-2 text-sm"
         href="{{ message_url }}">{% trans "Link" %}</a>
      {% if parent %}
      <a class="inline-block text-sm"
         href="{{ parent_url }}">{% trans "Parent" %}</a>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>

templates/private_messages/includes/message_list.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load private_messages %}

{% if page_obj.number > 1 %}
{% include "includes/pagination.html" with css_class="mb-3" %}
{% endif %}

{% if object_list %}
{% for message in object_list %}
{% render_message request user message %}
{% endfor %}
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}

templates/private_messages/includes/modal_message_form.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}
{% extends "includes/modal.html" %}

{% load i18n %}

{% block modal_header %}Send message{% endblock %}
{% block modal_content %}
{% include "includes/forms/form.html" with form_id="send-message-form" %}
{% endblock %}

templates/private_messages/includes/notification.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if verb == "reply" %}
{% blocktrans %}
<a href="{{ actor_url }}">
  {{ actor_display }}</a> has replied to your <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% elif verb == "follow_up" %}
{% blocktrans %}
<a href="{{ actor_url }}">
  {{ actor_display }}</a> has sent you a <a href="{{ object_url }}">follow-up</a> to one of
their messages.
{% endblocktrans %}
{% else %}
{% blocktrans %}
<a href="{{ actor_url }}">
  {{ actor_display }}</a> has sent you a <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% endif %}