localhub/activities/events/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


# Django
from django.urls import path

# Localhub
from localhub.activities.urls.generic import create_activity_urls

# Local
from . import views
from .forms import EventForm
from .models import Event

app_name = "events"


urlpatterns = create_activity_urls(
    Event,
    EventForm,
    detail_view=views.event_detail_view,
    create_view=views.event_create_view,
    list_view=views.event_list_view,
    update_view=views.event_update_view,
)

urlpatterns += [
    path("calendar/", views.event_calendar_view, name="calendar"),
    path("<int:pk>~attend/", views.event_attend_view, name="attend"),
    path(
        "<int:pk>~unattend/",
        views.event_attend_view,
        name="unattend",
        kwargs={"remove": True},
    ),
    path("<int:pk>~cancel/", views.event_cancel_view, name="cancel"),
    path("<int:pk>~download/", views.event_download_view, name="download"),
]

localhub/invites/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from . import views

app_name = "invites"


urlpatterns = [
    path("", views.invite_list_view, name="list"),
    path("received/", views.received_invite_list_view, name="received_list"),
    path("~create/", views.invite_create_view, name="create"),
    path("<pk>/~resend/", views.invite_resend_view, name="resend"),
    path("<pk>/~delete/", views.invite_delete_view, name="delete"),
    path("<pk>/~accept/", views.invite_accept_view, name="accept"),
    path("<pk>/~reject/", views.invite_reject_view, name="reject"),
    path("<pk>/", views.invite_detail_view, name="detail"),
]

localhub/notifications/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Local
from . import views

app_name = "notifications"

urlpatterns = [
    path("", views.notification_list_view, name="list"),
    path("service-worker.js", views.service_worker_view, name="service_worker"),
    path("~subscribe/", views.subscribe_view, name="subscribe"),
    path(
        "~unsubscribe/",
        views.subscribe_view,
        name="unsubscribe",
        kwargs={"remove": True},
    ),
    path("<int:pk>/~delete/", views.notification_delete_view, name="delete"),
    path("<int:pk>/~mark-read/", views.notification_mark_read_view, name="mark_read"),
    path("~delete-all/", views.notification_delete_all_view, name="delete_all"),
    path(
        "~mark-all-read/",
        views.notification_mark_all_read_view,
        name="mark_all_read",
    ),
]

localhub/tags/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from . import views

app_name = "activities"

urlpatterns = [
    path("", views.tag_list_view, name="tag_list"),
    path("following/", views.following_tag_list_view, name="following_tag_list",),
    path("blocked/", views.blocked_tag_list_view, name="blocked_tag_list"),
    path(
        "autocomplete/", views.tag_autocomplete_list_view, name="tag_autocomplete_list",
    ),
    path("<int:pk>/~follow/", views.tag_follow_view, name="tag_follow"),
    path("<int:pk>/~unfollow/", views.tag_unfollow_view, name="tag_unfollow",),
    path("<int:pk>/~block/", views.tag_block_view, name="tag_block"),
    path("<int:pk>/~unblock/", views.tag_unblock_view, name="tag_unblock"),
    path("<slug:slug>/", views.tag_detail_view, name="tag_detail"),
]

localhub/notifications/models/querysets.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


from django.db import models


class NotificationQuerySet(models.QuerySet):
    def for_community(self, community):
        """Filter notifications for a community, including
        only those with actors who are active members.

        Args:
            community (Community)

        Returns:
            QuerySet
        """

        return self.filter(
            community=community,
            actor__membership__community=community,
            actor__membership__active=True,
            actor__is_active=True,
        )

    def exclude_blocked_actors(self, recipient):
        """Exclude all notifications with actors blocked by the recipient.

        Args:
            recipient (User): notification recipient

        Returns:
            QuerySet
        """

        return self.exclude(actor__in=recipient.blocked.all())

    def for_recipient(self, recipient):
        """Return all notifications for a recipient

        Args:
            recipient (User): notification recipient

        Returns:
            QuerySet
        """

        return self.filter(recipient=recipient)

    def unread(self):
        """Return all notifications with is_read=False

        Returns:
            QuerySet
        """

        return self.filter(is_read=False)

    def mark_read(self):
        """Marks all notifications read if they are unread.

        Returns:
            int -- number updated
        """

        return self.unread().update(is_read=True)

localhub/activities/events/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Standard Library
import calendar
import datetime

# Django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_POST

# Third Party Libraries
import pytz
from dateutil import relativedelta
from turbo_response import TurboFrame

# Localhub
from localhub.activities.views.generic import (
    activity_detail_view,
    activity_update_view,
    get_activity_or_404,
    get_activity_queryset,
    handle_activity_create,
    render_activity_detail,
    render_activity_list,
)
from localhub.common.decorators import add_messages_to_response_header
from localhub.communities.decorators import community_required
from localhub.users.utils import has_perm_or_403

# Local
from .decorators import override_timezone
from .models import Event


@require_POST
@login_required
@community_required
@add_messages_to_response_header
def event_cancel_view(request, pk):
    event = get_object_or_404(get_activity_queryset(request, Event), pk=pk)
    has_perm_or_403(request.user, "events.cancel", event)

    event.canceled = timezone.now()
    event.save()
    event.notify_on_cancel(request.user)

    messages.success(request, _("This event has been canceled"))

    return redirect(event)


@require_POST
@login_required
@community_required
@add_messages_to_response_header
def event_attend_view(request, pk, remove=False):

    event = get_object_or_404(get_activity_queryset(request, Event), pk=pk)
    has_perm_or_403(request.user, "events.attend", event)

    if remove:
        event.attendees.remove(request.user)
        messages.info(request, _("You are no longer attending this event"))
    else:
        event.attendees.add(request.user)
        event.notify_on_attend(request.user)
        messages.success(request, _("You are now attending this event"))

    return (
        TurboFrame(event.get_dom_id() + "-attend")
        .template(
            "events/includes/attend.html",
            {"object": event, "is_attending": not (remove)},
        )
        .response(request)
    )


@community_required
@override_timezone
def event_download_view(request, pk):
    event = get_object_or_404(get_activity_queryset(request, Event), pk=pk)
    response = HttpResponse(content_type="text/calendar")
    response.write(event.to_ical())
    return response


@login_required
@community_required
@override_timezone
def event_create_view(request, model, form_class, **kwargs):

    has_perm_or_403(request.user, "activities.create_activity", request.community)

    try:
        [day, month, year] = [
            int(request.GET[param]) for param in ("day", "month", "year")
        ]
        starts = datetime.datetime(day=day, month=month, year=year, hour=9)
    except (KeyError, ValueError):
        starts = None

    initial = {"timezone": request.user.default_timezone, "starts": starts}

    return handle_activity_create(request, model, form_class, initial=initial, **kwargs)


event_update_view = override_timezone(activity_update_view)


event_detail_view = override_timezone(activity_detail_view)


@community_required
@override_timezone
def event_detail_view(request, model, pk, template_name, slug=None):
    event = get_activity_or_404(
        request,
        get_activity_queryset(
            request, model, with_common_annotations=True
        ).with_next_date(),
        pk=pk,
    )
    return render_activity_detail(request, event, template_name)


@community_required
@override_timezone
def event_list_view(request, model, template_name):
    qs = (
        get_activity_queryset(request, model, with_common_annotations=True)
        .with_relevance()
        .with_timedelta()
    )
    return render_activity_list(
        request, qs, template_name, ordering=("-relevance", "timedelta")
    )


@community_required
@override_timezone
def event_calendar_view(request):

    now = timezone.localtime(timezone.now())

    def _get_date_value(param, default):
        try:
            return int(request.GET[param])
        except (KeyError, ValueError):
            return default

    day, month, year = [
        _get_date_value(param, default)
        for param, default in [("day", None), ("month", now.month), ("year", now.year)]
    ]

    try:
        qs = (
            Event.objects.for_community(request.community)
            .published_or_owner(request.user)
            .with_next_date()
            .exclude_blocked(request.user)
            .filter(parent__isnull=True)
            .order_by("next_date")
        )

        if day:
            qs = qs.for_date(day, month, year).with_common_annotations(
                request.user, request.community
            )
        else:
            qs = qs.for_month(month, year)
    except Event.InvalidDate:
        raise Http404("Invalid date")

    context = {}

    if day:
        match_datetime = make_datetime(day, month, year)

        context = {
            "current_date": make_date(day, month, year),
            "events": [event for event in qs if event.matches_date(match_datetime)],
        }

    else:
        first_of_month = make_date(1, month, year)
        context = {
            "events": qs,
            "current_month": first_of_month,
            "next_month": first_of_month + relativedelta.relativedelta(months=+1),
            "previous_month": first_of_month + relativedelta.relativedelta(months=-1),
            "today": now,
            "is_current_month": now.month == first_of_month.month
            and now.year == first_of_month.year,
            "slots": [
                (
                    day,
                    is_past,
                    [event for event in qs if dt and event.matches_date(dt)],
                )
                for day, is_past, dt in iter_dates(day, month, year)
            ],
        }
    return TemplateResponse(request, "events/calendar.html", context)


def make_datetime(day, month, year):
    try:
        return timezone.localtime(
            datetime.datetime(
                day=day,
                month=month,
                year=year,
                tzinfo=pytz.UTC,
            )
        )
    except ValueError:
        raise Http404("Invalid date")


def make_date(day, month, year):
    return make_datetime(day, month, year).date()


def is_past(day, month, year):
    now = timezone.now()
    # any month in the future
    if month > now.month and year >= now.year:
        return False

    # any month in the past
    if month < now.month:
        return True

    # this month
    return now.day > day


def iter_dates(day, month, year):
    """Yields tuple of (counter, is_past, datetime) for each day of month. If day
    falls out of range yields zero, False, None.
    """
    try:
        for day in calendar.Calendar().itermonthdays(year, month):
            if day > 0:
                yield day, is_past(day, month, year), make_datetime(day, month, year)
            else:
                # falls outside the day range
                yield 0, False, None
    except ValueError:
        raise Http404("Invalid date")

localhub/apps/events/views/list.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

import calendar
import datetime

from django.http import Http404
from django.utils import timezone
from django.utils.functional import cached_property
from django.views.generic.dates import DateMixin, DayMixin, MonthMixin, YearMixin

import pytz

from localhub.apps.activities.views.list_detail import (
    ActivityListView,
    BaseActivityListView,
)

from ..models import Event


class EventListView(ActivityListView):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_relevance()
            .with_timedelta()
            .order_by("-relevance", "timedelta")
        )


class EventCalendarView(
    YearMixin, MonthMixin, DayMixin, DateMixin, BaseActivityListView
):
    template_name = "events/calendar.html"
    date_field = "starts"
    paginate_by = None
    allow_future = True
    model = Event

    def get_allow_empty(self):
        # empty month view is fine, but you should not be able
        # to navigate to a single date missing any events.
        return not (self.current_day)

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Event.InvalidDate:
            raise Http404("These dates are not valid")

    @cached_property
    def current_day(self):
        try:
            return int(self.get_day())
        except (Http404, ValueError):
            return None

    @cached_property
    def current_month(self):
        try:
            return int(self.get_month())
        except (Http404, ValueError):
            return timezone.now().month

    @cached_property
    def current_year(self):
        try:
            return int(self.get_year())
        except (Http404, ValueError):
            return timezone.now().year

    def get_queryset(self):
        # for rep
        qs = (
            super()
            .get_queryset()
            .published_or_owner(self.request.user)
            .with_next_date()
            .exclude_blocked(self.request.user)
            .filter(parent__isnull=True)
            .order_by("next_date")
        )
        if self.current_day:
            qs = qs.for_date(self.current_day, self.current_month, self.current_year)
        else:
            qs = qs.for_month(self.current_month, self.current_year)
        return qs

    def make_date(self, day):
        try:
            return datetime.date(
                day=day, month=self.current_month, year=self.current_year,
            )
        except ValueError:
            raise Event.InvalidDate()

    def make_datetime(self, day):
        try:
            return datetime.datetime(
                day=day,
                month=self.current_month,
                year=self.current_year,
                tzinfo=pytz.UTC,
            )
        except ValueError:
            raise Event.InvalidDate()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        if self.current_day:
            data["current_date"] = self.make_date(self.current_day)
            match_datetime = self.make_datetime(self.current_day)
            data["events"] = [
                event
                for event in self.object_list
                if event.matches_date(match_datetime)
            ]
            return data

        now = timezone.now()

        data["current_month"] = first_of_month = self.make_date(1)

        data.update(
            {
                "next_month": self.get_next_month(first_of_month),
                "previous_month": self.get_previous_month(first_of_month),
                "slots": self.get_slots(),
                "today": now,
                "is_today": now.month == first_of_month.month
                and now.year == first_of_month.year,
            }
        )

        return data

    def get_slots(self):
        """Group events by day into tuples of (number, events)
        """

        return [
            (
                day,
                is_past,
                [event for event in self.object_list if dt and event.matches_date(dt)],
            )
            for day, is_past, dt in self.iter_dates()
        ]

    def is_past(self, day):
        now = timezone.now()
        # any month in the future
        if self.current_month > now.month and self.current_year >= now.year:
            return False

        # any month in the past
        if self.current_month < now.month:
            return True

        # this month
        return now.day > day

    def iter_dates(self):
        """Yields tuple of (counter, is_past, datetime) for each day of month. If day
        falls out of range yields zero, False, None.
        """
        try:
            for day in calendar.Calendar().itermonthdays(
                self.current_year, self.current_month
            ):
                if day > 0:
                    yield day, self.is_past(day), self.make_datetime(day=day)
                else:
                    # falls outside the day range
                    yield 0, False, None
        except ValueError:
            raise Event.InvalidDate()


event_calendar_view = EventCalendarView.as_view()

templates/events/includes/actions.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/actions.html" %}

{% load i18n %}
{% load rules %}

{% block extra_actions %}

{% has_perm "events.attend" user object as can_attend %}

{% if can_attend %}
<turbo-frame id="{{ object.get_dom_id }}-attend">
  {% include "events/includes/attend.html" with is_attending=object.is_attending %}
</turbo-frame>
{% endif %}

{% if object.is_attendable %}
<a href="{% url 'events:download' object.id %}"
   class="dropdown-menu-item"
   role="button"
   data-turbo="false"
   download>
  {% trans 'Download' %}
</a>
{% endif %}

{% has_perm "events.cancel" user object as can_cancel %}
{% if can_cancel %}
<form method="post"
      action="{% url 'events:cancel' object.id %}"
      data-controller="confirm"
      data-action="confirm#confirm"
      data-confirm-text-value="{% trans 'Are you sure you want to cancel this event?' %}">
  {% csrf_token %}
  <button class="dropdown-menu-item">{% trans "Cancel Event" %}</button>
</form>
{% endif %}


{% endblock %}

templates/events/includes/attend.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}

<form method="post"
      action="{% if is_attending %}{% url 'events:unattend' object.id %}{% else %}{% url 'events:attend' object.id %}{% endif %}">
  {% csrf_token %}
  {% if is_attending %}
  <button class="dropdown-menu-item line-through">{% translate "Attending" %}</button>
  {% else %}
  <button class="dropdown-menu-item">{% translate "Attending" %}</button>
  {% endif %}
</form>

templates/events/includes/calendar.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
<div class="border-gray-500 min-w-100">
  <div class="flex items-center justify-between bg-indigo-900 text-white px-4 py-2 font-semibold border-r border-l border-t border-gray-500">
    <a class="text-sm text-white hover:text-gray-200"
       href="{{ request.path }}?month={{ previous_month.month }}&year={{ previous_month.year }}">
      {% trans "Previous" %}
    </a>
    <div class="font-semibold">{{ current_month|date:"F Y" }}</div>
    <a class="text-sm text-white hover:text-gray-200"
       href="{{ request.path }}?month={{ next_month.month }}&year={{ next_month.year }}">
      {% trans "Next" %}
    </a>
  </div>
  <div class="flex flex-wrap justify-between text-center items-center py-4 px-0 bg-blue-600 text-white font-semibold border-r border-l border-gray-500">
    <div class="text-sm calendar-item">{% trans "Mon" %}</div>
    <div class="text-sm calendar-item">{% trans "Tue" %}</div>
    <div class="text-sm calendar-item">{% trans "Wed" %}</div>
    <div class="text-sm calendar-item">{% trans "Thu" %}</div>
    <div class="text-sm calendar-item">{% trans "Fri" %}</div>
    <div class="text-sm calendar-item">{% trans "Sat" %}</div>
    <div class="text-sm calendar-item">{% trans "Sun" %}</div>
  </div>
  <div class="flex flex-wrap border-l border-gray-500">
    {% for day, is_past, events in slots %}
    {% with num_events=events|length %}
    <div class="calendar-item text-xs{% if not day %} bg-gray-200{% elif day == today.day and is_current_month %} bg-blue-600 {% if num_events %}hover:bg-blue-500{% endif %} text-white{% elif num_events %} bg-indigo-900 text-white hover:bg-indigo-700{% else %} bg-white{% endif %}{% if num_events %} cursor-pointer focus:outline-none{% endif %}"
         {% if num_events %}
         data-controller="linkify"
         data-action="click->linkify#fetch"
         data-linkify-url-value="{% if num_events == 1 %}{{ events.0.get_absolute_url }}{% else %}{{ request.path }}?day={{ day }}&month={{ current_month.month }}&year={{ current_month.year }}{% endif %}"
         {% endif %}>
      {% if day %}
      {% comment %}
      {% elif can_create_activity %}
      {% endcomment %}
      {% if can_create_activity and not events %}
      <div class="h-10 lg:h-32 p-2 border-b border-r border-gray-500 cursor-pointer focus:outline-none"
           data-controller="linkify"
           data-action="click->linkify#fetch"
           data-linkify-url-value="{% url 'events:create' %}?day={{ day }}&month={{ current_month.month }}&year={{ current_month.year }}">
        {% else %}
        <div class="h-10 lg:h-32 p-2 tracking-tight border-r border-b border-gray-500 align-middle">
          {% endif %}
          <button>
            {{ day }}
            <span class="lg:hidden ml-1">
              {% for event in events|slice:5 %}&middot;{% endfor %}
            </span>
          </button>
          <div class="clear-both"></div>
          {% if events %}
          <div class="hidden lg:block text-xs{% if is_past %} text-gray-500{% endif %}">
            {% for event in events|slice:":2" %}

            <div class="{% if not event.is_attendable %} line-through{% elif event.is_attending %} font-semibold{% endif %}">{{ event.title }}</div>

            {% endfor %}

            {% if num_events > 2 %}
            <div href="#">{{ num_events|add:"-2" }} {% trans "More..." %}
            </div>
            {% endif %}

          </div>
          {% endif %}
        </div>
        {% else %}
        <div class="h-10 lg:h-32 p-2 border-b border-r border-gray-500"></div>
        {% endif %}
      </div>
      {% endwith %}
      {% endfor %}
    </div>
  </div>

templates/events/includes/calendar_desktop.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "events/includes/calendar.html" %}
{% load i18n %}

{% block calendar_date %}
<button class="date-item{% if day == today.day and is_today %} date-today{% endif %}">{{ day }}</button>
{% if events_for_day %}
<div class="calendar-events">
  {% for event in events_for_day|slice:"0,3" %}

  <a class="calendar-event{% if not event.is_attendable %} text-strike{% elif event.is_attending %} text-bold{% endif %}"
     href="{{ event.get_absolute_url }}"
     title="{{ event.title }}">{{ event.title }}</a>
  {% endfor %}

  {% if num_events > 3 %}
  <a class="calendar-event"
     href="{{ request.path }}?day={{ day }}&month={{ current_month.month }}&year={{ current_month.year }}"
     href="">{{ num_events|add:"-3" }} {% trans "More..." %}</a>
  {% endif %}

</div>
{% endif %}
{% endblock calendar_date %}

templates/events/includes/calendar_mobile.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "events/includes/calendar.html" %}

{% load i18n %}

{% block calendar_date %}
{% if num_events %}
<a href="{{ request.path }}?day={{ day }}&month={{ current_month.month }}&year={{ current_month.year }}"
   class="date-item badge{% if day == today.day and is_today %} date-today{% endif %}">{{ day }}</a>
{% else %}
<button class="date-item{% if day == today.day and is_today %} date-today{% endif %}">{{ day }}</button>
{% endif %}
{% endblock %}

templates/events/includes/event.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/activity_base.html" %}

{% load i18n %}

{% load tz %}
{% load activities %}


{% block header %}
{{ block.super }}
{% if object.canceled %}
<p class="font-bold mb-3">{% trans "This event has been canceled." %}</p>
{% endif %}
{% endblock header %}

{% block content %}
{% with starts=object.get_next_start_date ends=object.get_next_end_date %}

<dl class="text-sm">

  {% timezone object.timezone %}
  {% if ends %}

  {% with start_date=starts|date:"SHORT_DATE_FORMAT" end_date=ends|date:"SHORT_DATE_FORMAT" start_time=starts|date:"TIME_FORMAT" end_time=ends|date:"TIME_FORMAT" %}

  {% if start_date == end_date %}

  <dt>
    {% trans "Date" %} <span class="tag">{{ object.timezone }}</span>
  </dt>

  <dd{% if not object.is_attendable %} class="line-through"
                                       {% endif %}>
    {{ starts|date:"D" }} {{ start_date }} @ {{ start_time }} - {{ end_time }}
    </dd>

    {% else %}
    <dt>{% trans "Dates" %} <span class="tag">{{ object.timezone }}</span></dt>

    <dd{% if not object.is_attendable %} class="line-through"
                                         {% endif %}>
      {{ starts|date:"D" }} {{ start_date }} @ {{ start_time }} - {{ ends|date:"D" }} {{ end_date }} @ {{ end_time }}</dd{%>
    {% endif %} {% endwith %}
                            {% else %}
                            <dt>{% trans "Date" %} <span class="tag">{{ object.timezone }}</span></dt>
    <dd{% if not object.is_attendable %} class="line-through"
                                         {% endif %}>
      {{ starts|date:"D" }} {{ starts|date:"SHORT_DATE_FORMAT" }} @ {{ starts|date:"TIME_FORMAT" }}
    </dd{%>

   {% endif %} {% if object.repeats %}
                            <dt>{% trans "Repeats" %}</dt>
    <dd>
      {% if object.repeats_weekly %}
      {% blocktrans with weekday=object.starts|date:"l" %}
      Same time every {{ weekday }}
      {% endblocktrans %}
      {% else %}
      {{ object.get_repeats_display }}
      {% endif %}
      {% if object.repeats_until %}
      {% blocktrans with until=object.repeats_until|date:"SHORT_DATE_FORMAT" %}
      until {{ until }}
      {% endblocktrans %}
      {% endif %}
    </dd>
    {% endif %}

    {% endtimezone %}
    {% with location=object.get_full_location %}
    {% if location %}
    <dt>{% trans "Location" %}</dt>
    <dd>
      {% if not is_detail and object.has_map %}
      <a href="{{ object.get_absolute_url }}#map-for-event-{{ object.id }}">{{ location }}</a>
      {% else %}
      {{ location }}
      {% endif %}
    </dd>
    {% endif %}
    {% endwith %}

    {% if object.url %}
    <dt>{% trans "URL" %}</dt>
    <dd class="truncate">{{ object.url|urlize }}</dd>
    {% endif %}


    {% if object.is_detail %}

    {% if object.contact_name %}
    <dt>{% trans "Contact" %}</dt>
    <dd>{{ object.contact_name }}</dd>
    {% endif %}

    {% if object.contact_email %}
    <dt>{% trans "Email" %}</dt>
    <dd>{{ object.contact_email|urlize }}</dd>
    {% endif %}

    {% if object.contact_phone %}
    <dt>{% trans "Phone" %}</dt>
    <dd>{{ object.contact_phone|phone2numeric }}</dd>
    {% endif %}

    {% if object.ticket_price %}
    <dt>{% trans "Admission" %}</dt>
    <dd>{{ object.ticket_price }}</dd>
    {% endif %}

    {% if object.ticket_vendor %}
    <dt>{% trans "Tickets available from" %}</dt>
    <dd>{{ object.ticket_vendor|linebreaksbr }}</dd>
    {% endif %}

    {% endif %}

</dl>

{% if is_detail %}
{% include "activities/includes/map.html" with css_class="pb-1" %}
{% endif %}

{% with user|is_oembed_url:object.url as is_oembed %}
{% include "activities/includes/oembed.html" %}
{% endwith %}
{% include "activities/includes/description.html" %}

{% if object.is_canceled %}
</div>
{% endif %}

{% endwith %}
{% endblock content %}

{% block actions %}{% include "events/includes/actions.html" %}{% endblock %}
{% block info %}{% include "events/includes/info.html" %}{% endblock %}
{% block links %}{% include "events/includes/links.html" %}{% endblock %}

templates/events/includes/event_pinned.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/activity_pinned_base.html" %}

{% block actions %}{% include "events/includes/actions.html" %}{% endblock %}

templates/events/includes/links.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "activities/includes/links.html" %}

{% load i18n %}

{% block extra_links %}
{% if object.has_map and not is_detail %}
<a class="text-sm" href="{{ object.get_absolute_url }}#map-for-event-{{ object.id }}">{% trans "Map" %}</a>
{% endif %}
{% endblock %}