localhub/private_messages/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path

# Localhub
from localhub.users.urls import user_re_path

# Local
from . import views

app_name = "private_messages"

urlpatterns = [
    path("inbox/", views.inbox_view, name="inbox"),
    path("outbox/", views.outbox_view, name="outbox"),
    path("send/", views.message_create_view, name="message_create"),
    path("~/mark-read/", views.message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", views.message_detail_view, name="message_detail"),
    path("message/<int:pk>/~reply/", views.message_reply_view, name="message_reply"),
    path(
        "message/<int:pk>/~follow-up/",
        views.message_reply_view,
        name="message_follow_up",
        kwargs={"is_follow_up": True},
    ),
    path("message/<int:pk>/~delete/", views.message_delete_view, name="message_delete"),
    path(
        "message/<int:pk>/~read/",
        views.message_mark_read_view,
        name="message_mark_read",
    ),
    path(
        "message/<int:pk>/~bookmark/",
        views.message_bookmark_view,
        name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        views.message_bookmark_view,
        name="message_remove_bookmark",
        kwargs={
            "remove": True,
        },
    ),
    user_re_path(
        r"~send/$",
        views.message_recipient_create_view,
        name="message_create_recipient",
    ),
]

localhub/tags/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from . import views

app_name = "activities"

urlpatterns = [
    path("", views.tag_list_view, name="tag_list"),
    path("following/", views.following_tag_list_view, name="following_tag_list",),
    path("blocked/", views.blocked_tag_list_view, name="blocked_tag_list"),
    path(
        "autocomplete/", views.tag_autocomplete_list_view, name="tag_autocomplete_list",
    ),
    path("<int:pk>/~follow/", views.tag_follow_view, name="tag_follow"),
    path("<int:pk>/~unfollow/", views.tag_unfollow_view, name="tag_unfollow",),
    path("<int:pk>/~block/", views.tag_block_view, name="tag_block"),
    path("<int:pk>/~unblock/", views.tag_unblock_view, name="tag_unblock"),
    path("<slug:slug>/", views.tag_detail_view, name="tag_detail"),
]

localhub/users/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.urls import path, re_path

# Local
from . import views

app_name = "users"

USERNAME_RE = r"^(?P<username>[\w.@+-]+)/"


def user_re_path(path, *args, **kwargs):
    return re_path(USERNAME_RE + path, *args, **kwargs)


urlpatterns = [
    path("autocomplete/", views.user_autocomplete_list_view, name="autocomplete_list"),
    path("members/", views.member_list_view, name="member_list"),
    path("following/", views.following_user_list_view, name="following_list"),
    path("followers/", views.follower_user_list_view, name="follower_list"),
    path("blocked/", views.blocked_user_list_view, name="blocked_list"),
    user_re_path(r"likes/$", views.user_activity_likes_view, name="activity_likes"),
    user_re_path(
        r"likes/comments/$",
        views.user_comment_likes_view,
        name="comment_likes",
    ),
    user_re_path(
        r"mentions/$",
        views.user_activity_mentions_view,
        name="activity_mentions",
    ),
    user_re_path(
        r"mentions/comments/$",
        views.user_comment_mentions_view,
        name="comment_mentions",
    ),
    user_re_path(r"follow/$", views.user_follow_view, name="follow"),
    user_re_path(
        r"unfollow/$", views.user_follow_view, name="unfollow", kwargs={"remove": True}
    ),
    user_re_path(r"block/$", views.user_block_view, name="block"),
    user_re_path(
        r"unblock/$", views.user_block_view, name="unblock", kwargs={"remove": True}
    ),
    user_re_path(r"comments/$", views.user_comment_list_view, name="comments"),
    user_re_path(r"messages/$", views.user_message_list_view, name="messages"),
    user_re_path(r"$", views.user_stream_view, name="activities"),
]

localhub/communities/views/base.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class CommunityRequiredMixin(LoginRequiredMixin):
    """
    Ensures that a community is available on this domain. This requires
    the CurrentCommunityMiddleware is enabled.

    If the user is not a member they will be redirected to the Welcome view.

    If the view has the `allow_non_members` property *True* then the above
    rule is overriden - for example in some cases where we want to allow
    the user to be able to handle an invitation.
    """

    allow_non_members = False

    def dispatch(self, request, *args, **kwargs):
        if not request.community.active:
            return self.handle_community_not_found()

        if (
            request.user.is_authenticated
            and not request.user.has_perm(
                "communities.view_community", request.community
            )
            and not self.allow_non_members
        ):
            return self.handle_community_access_denied()
        return super().dispatch(request, *args, **kwargs)

    def handle_community_access_denied(self):
        if self.request.is_ajax():
            raise PermissionDenied(_("You must be a member of this community"))
        return HttpResponseRedirect(reverse("community_welcome"))

    def handle_community_not_found(self):
        if self.request.is_ajax():
            raise Http404(_("No community is available for this domain"))
        return HttpResponseRedirect(reverse("community_not_found"))

localhub/private_messages/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

# Django
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import F
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_POST

# Third Party Libraries
from turbo_response import TurboFrame, TurboStream, redirect_303, render_form_response

# Localhub
from localhub.bookmarks.models import Bookmark
from localhub.common.decorators import add_messages_to_response_header
from localhub.common.pagination import render_paginated_queryset
from localhub.communities.decorators import community_required
from localhub.users.utils import has_perm_or_403

# Local
from .forms import MessageForm, MessageRecipientForm
from .models import Message


@login_required
@community_required
def message_reply_view(request, pk, is_follow_up=False):

    has_perm_or_403(request.user, "private_messages.create_message", request.community)

    qs = (
        Message.objects.for_community(request.community)
        .exclude_blocked(request.user)
        .common_select_related()
    )

    if is_follow_up:
        qs = qs.for_sender(request.user)
    else:
        qs = qs.for_recipient(request.user)

    parent = get_object_or_404(qs, pk=pk)
    recipient = parent.get_other_user(request.user)

    if request.method == "POST":
        form = MessageForm(request.POST)

        if form.is_valid():

            message = form.save(commit=False)
            message.community = request.community
            message.sender = request.user
            message.recipient = recipient
            message.parent = parent
            message.save()

            message.notify_on_reply()

            messages.success(
                request,
                _("Your message has been sent to %(recipient)s")
                % {"recipient": recipient.get_display_name()},
            )

            return redirect_303(message)

    else:
        form = MessageForm()

    form["message"].label = (
        _("Send follow-up to %(recipient)s")
        if is_follow_up
        else _("Send reply to %(recipient)s")
    ) % {"recipient": recipient.get_display_name()}

    return render_form_response(
        request,
        form,
        "private_messages/message_form.html",
        {"recipient": recipient, "parent": parent},
    )


@login_required
@community_required
@add_messages_to_response_header
def message_recipient_create_view(request, username):

    has_perm_or_403(request.user, "private_messages.create_message", request.community)

    recipient = get_object_or_404(
        get_user_model()
        .objects.exclude(pk=request.user.id)
        .for_community(request.community)
        .exclude_blocking(request.user),
        username__iexact=username,
    )
    stream = TurboStream("modal")

    if request.method == "POST":
        form = MessageForm(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            message.community = request.community
            message.sender = request.user
            message.recipient = recipient
            message.save()

            message.notify_on_send()

            messages.success(
                request,
                _("Your message has been sent to %(recipient)s")
                % {"recipient": recipient.get_display_name()},
            )

            return stream.update.response()
    else:
        form = MessageForm()

    form["message"].label = _(
        "Send message to %(recipient)s" % {"recipient": recipient.get_display_name()}
    )

    return stream.update.template(
        "private_messages/includes/modal_message_form.html",
        {"form": form, "recipient": recipient},
    ).response(request)


@login_required
@community_required
def message_create_view(request):

    if request.method == "POST":
        form = MessageRecipientForm(
            request.POST, community=request.community, sender=request.user
        )

        if form.is_valid():
            message = form.save(commit=False)
            message.community = request.community
            message.sender = request.user
            message.save()
            message.notify_on_send()

            messages.success(
                request,
                _("Your message has been sent to %(recipient)s")
                % {"recipient": message.recipient.get_display_name()},
            )

            return redirect_303(message)

    else:
        form = MessageRecipientForm(community=request.community, sender=request.user)

    return render_form_response(
        request,
        form,
        "private_messages/message_form.html",
    )


@login_required
@community_required
def inbox_view(request):
    messages = (
        Message.objects.for_community(community=request.community)
        .with_has_bookmarked(request.user)
        .for_recipient(request.user)
        .exclude_blocked(request.user)
        .common_select_related()
    )
    if search := request.GET.get("q"):
        messages = messages.search(search).order_by("-rank", "-created")
    else:
        messages = messages.order_by(F("read").desc(nulls_first=True), "-created")

    return render_paginated_queryset(
        request,
        messages,
        "private_messages/inbox.html",
        {"search": search},
    )


@login_required
@community_required
def outbox_view(request):
    messages = (
        Message.objects.for_community(community=request.community)
        .with_has_bookmarked(request.user)
        .for_sender(request.user)
        .exclude_blocked(request.user)
        .common_select_related()
    )
    if search := request.GET.get("q"):
        messages = messages.search(search).order_by("-rank", "-created")
    else:
        messages = messages.order_by("-created")

    return render_paginated_queryset(
        request,
        messages,
        "private_messages/outbox.html",
        {"search": search},
    )


@login_required
@community_required
def message_detail_view(request, pk):
    message = get_object_or_404(
        Message.objects.for_community(request.community)
        .for_sender_or_recipient(request.user)
        .exclude_blocked(request.user)
        .with_has_bookmarked(request.user)
        .common_select_related(),
        pk=pk,
    )

    if message.recipient == request.user:
        message.mark_read(mark_replies=True)

    return TemplateResponse(
        request,
        "private_messages/message_detail.html",
        {
            "message": message,
            "parent": message.get_parent(request.user),
            "other_user": message.get_other_user(request.user),
            "replies": (
                message.get_all_replies()
                .for_sender_or_recipient(request.user)
                .common_select_related()
                .order_by("created")
                .distinct()
            ),
        },
    )


@login_required
@community_required
def message_mark_all_read_view(request):
    Message.objects.for_community(request.community).for_recipient(
        request.user
    ).unread().mark_read()
    return redirect("private_messages:inbox")


@login_required
@community_required
def message_mark_read_view(request, pk):

    message = get_object_or_404(
        Message.objects.for_community(request.community)
        .for_recipient(request.user)
        .unread(),
        pk=pk,
    )
    message.mark_read()

    return TurboStream(f"message-{message.id}-mark-read").remove.response()


@require_POST
@login_required
@community_required
@add_messages_to_response_header
def message_bookmark_view(request, pk, remove=False):
    message = get_object_or_404(
        Message.objects.for_community(request.community).for_sender_or_recipient(
            request.user
        ),
        pk=pk,
    )
    if remove:
        Bookmark.objects.filter(user=request.user, message=message).delete()
        messages.info(request, _("Your bookmark has been removed"))
    else:

        try:
            Bookmark.objects.create(
                user=request.user,
                community=request.community,
                content_object=message,
            )
            messages.success(request, _("You have bookmarked this message"))
        except IntegrityError:
            pass

    return (
        TurboFrame(f"message-{message.id}-bookmark")
        .template(
            "private_messages/includes/bookmark.html",
            {"object": message, "has_bookmarked": not (remove)},
        )
        .response(request)
    )


@require_POST
@login_required
@community_required
@add_messages_to_response_header
def message_delete_view(request, pk):

    message = get_object_or_404(
        Message.objects.for_community(request.community).for_sender_or_recipient(
            request.user
        ),
        pk=pk,
    )

    message.soft_delete(request.user)

    messages.info(request, _("Message has been deleted"))

    if "redirect" in request.POST:
        return redirect(
            "private_messages:inbox"
            if message.recipient == request.user
            else "private_messages:outbox"
        )

    return TurboStream(f"message-{pk}").remove.response()

localhub/private_messages/views/list.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.db.models import F
from django.views.generic import ListView

from localhub.views import SearchMixin

from .mixins import RecipientQuerySetMixin, SenderQuerySetMixin


class BaseMessageListView(SearchMixin, ListView):
    paginate_by = settings.LOCALHUB_DEFAULT_PAGE_SIZE


class InboxView(RecipientQuerySetMixin, BaseMessageListView):
    """
    Messages received by current user
    oere we should show the sender, timestamp...
    """

    template_name = "private_messages/inbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by(F("read").desc(nulls_first=True), "-created")


inbox_view = InboxView.as_view()


class OutboxView(SenderQuerySetMixin, BaseMessageListView):
    """
    Messages sent by current user
    """

    template_name = "private_messages/outbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by("-created")


outbox_view = OutboxView.as_view()

templates/private_messages/base.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "base.html" %}

{% load i18n %}
{% block subtitle %} / {% trans "Messages" %}{% endblock %}

templates/private_messages/conversation.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/base.html" %}

{% load i18n %}
{% load account %}
{% load rules %}
{% load private_messages_tags %}
{% load users_tags %}

{% block private_messages_subtitle %} | {% user_display user_obj %}{% endblock %}

{% block content %}
<h3>{% trans "Messages" %}</h3>
<h4>
    {% avatar user_obj "avatar-lg" %}
    <a href="{{ user_obj.get_absolute_url }}">{% user_display user_obj %}</a>
</h4>
<div class="actions" data-controller="toggle">
      {% get_unread_message_count user community as unread_messages %}
      <span {% if unread_messages %}class="badge" data-badge="{{ unread_messages }}"{% endif %}>
        <a href="{% url 'private_messages:inbox'%}">{% trans "Inbox" %}</a>
      </span>

    <a href="{% url 'private_messages:outbox' %}">{% trans "Outbox" %}</a>
    {% has_perm "private_messages.create_message" user community as can_create_message %}

    {% if can_create_message and user not in user_obj.blocked.all %}
    <a href="{% url 'private_messages:message_create' user_obj.username %}">{% trans "Send Message" %}</a>
    {% endif %}

</div>
<div class="divider"></div>

{% if paginator.count or view.search_query %}
{% include "includes/search_form.html" %}
{% endif %}

{% include "private_messages/includes/email_settings.html" %}

{% if object_list %}
{% for message in object_list %}
<div class="card mb-1 {% if message.sender == user %} bg-gray{% endif %}">
    <div class="card-header">
        <div class="card-title h6">
            <span class="timesince">
                {% blocktrans with created=message.created|timesince %}
                Sent {{ created }} ago by
                {% endblocktrans %}
                {% include "users/includes/chip.html" with profile=message.sender %}
                {% include "private_messages/includes/parent.html" %}
            </span>
        </div>
    </div>
    <div class="card-body">
        {% include "private_messages/includes/message.html" %}
    </div>
    <div class="card-footer">
        <div class="actions">
            <a href="{{ message.get_permalink }}">{% trans "Permalink" %}</a>
            {% if message.sender == request.user %}

            <a href="{% url 'private_messages:message_update' message.id %}">{% trans "Edit" %}</a>

            <a href="{% url 'private_messages:message_delete' message.id %}"
               data-controller="ajax confirm"
               data-action="confirm#check ajax#delete"
               data-ajax-redirect="{{ request.path }}"
               data-confirm-header="{% trans 'Delete' %}"
               data-confirm-body="{% trans 'Are you sure you want to delete this message?' %}"
               >{% trans "Delete" %}</a>

            {% elif not message.read %}
            <a href="{% url 'private_messages:message_mark_read' message.id %}"
               data-controller="ajax"
               data-action="ajax#post"
               data-ajax-redirect="{{ request.path }}"
               >{% trans "Mark As Read" %}</a>
            {% endif %}
            {% include "private_messages/includes/replies.html" %}
        </div>
    </div>
</div>
{% endfor %}
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}
{% endblock %}

templates/private_messages/inbox.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/message_list_base.html" %}

{% load i18n %}

{% block subtitle %}{{ block.super }} / {% translate "Inbox" %}{% endblock %}

{% block message_list %}

{% if paginator.count or search %}
{% include "includes/forms/search_form.html" with selector=True %}
{% endif %}

{% include "private_messages/includes/email_settings.html" %}
{% translate "You have not received any messages" as t_empty_message %}
{% include "private_messages/includes/message_list.html" with empty_message=t_empty_message %}
{% endblock message_list %}

templates/private_messages/message_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1 class="page-header">{% trans "Delete Message" %}</h1>

<form method="POST"
      action="{{ request.path }}">
  {% csrf_token %}
  <p>{% trans "Do you really want to delete this message?" %}</p>
  <a class="btn btn-link"
     href="{{ message.get_absolute_url }}">{% trans "Cancel" %}</a>
  <button class="btn btn-primary"
          type="submit">{% trans "Delete" %}</button>
</form>

{% endblock content %}

templates/private_messages/message_detail.html
{% extends "private_messages/base.html" %}

{% load i18n %}
{% load account %}
{% load rules %}
{% load private_messages %}

{% block content %}

<div class="flex-wrap lg:flex items-center lg:justify-between mb-3">
  {% if parent %}
  <ul class="breadcrumbs">
    <li class="breadcrumb-item">
      <a href="{{ parent.get_absolute_url }}">{% trans "Parent" %}</a>
    </li>
    <li class="breadcrumb-item">{% trans "Message" %}</li>
  </ul>
  {% endif %}

  {% has_perm "private_messages.create_message" user community as can_create_message %}

  <div class="page-nav mt-3 lg:mt-0">
    <a class="page-nav-item"
       href="{% url 'private_messages:inbox' %}">{% trans "Inbox" %}</a>
    <a class="page-nav-item"
       href="{% url 'private_messages:outbox' %}">{% trans "Outbox" %}</a>
    {% if can_create_message %}
    <a class="page-nav-item"
       data-turbo-frame="modal"
       href="{% url 'private_messages:message_create_recipient' other_user.username %}">
      {% user_display other_user as other_user_name %}
      {% blocktrans %}
      Send Message to {{ other_user_name }}
      {% endblocktrans %}
    </a>
    {% endif %}
  </div>
</div>

{% render_message request user message is_detail=True %}
{% for reply in replies %}
{% render_message request user reply conversation=message %}
{% endfor %}
{% endblock content %}

templates/private_messages/message_form.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/base.html" %}

{% load i18n %}
{% load account %}
{% load private_messages %}

{% block subtitle %}{% if recipient %} / {% user_display recipient %}{% endif %} /
{{ parent|yesno:_("Reply,Send Message") }} {% endblock %}

{% block content %}

{% if parent or recipient %}
<ul class="breadcrumbs mb-3">
  {% if parent %}
  <li class="breadcrumb-item"><a href="{{ parent.get_absolute_url }}">{% trans "Parent" %}</a></li>
  <li class="breadcrumb-item">
    <a href="#">
      {% if parent.sender == user %}{% trans "Follow-Up" %}{% else %}{% trans "Reply" %}{% endif %}
    </a>
  </li>
  {% elif recipient %}
  <li class="breadcrumb-item"><a href="{% url 'users:messages' recipient.username %}">{% user_display recipient %}</a>
  </li>
  <li class="breadcrumb-item">
    {% trans "Send Message" %}
  </li>
  {% endif %}
</ul>
{% endif %}

{% if parent %}
{% render_message request user parent is_detail=True %}
{% else %}
<h1 class="page-header mb-3">{% trans "Send Message" %}</h1>
{% endif %}

{% include "includes/forms/form.html" %}


{% endblock %}

templates/private_messages/message_list_base.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/base.html" %}

{% load i18n %}
{% load rules %}
{% load private_messages %}

{% block content %}

{% has_perm "private_messages.create_message" user community as can_create_message %}

<h1 class="page-header mb-3">{% trans "Messages" %}</h1>
{% with search=view.search_query %}
<div class="tabs text-sm mb-3">

  {% active_link 'private_messages:inbox' as link %}
  <a class="tab-item{% if link.match %} active{% endif %}"
     href="{{ link.url }}{% if search %}?q={{ search }}{% endif %}">{% trans "Inbox" %}</a>
  {% active_link 'private_messages:outbox' as link %}
  <a class="tab-item{% if link.match %} active{% endif %}"
     href="{{ link.url }}{% if search %}?q={{ search }}{% endif %}">{% trans "Outbox" %}</a>

  {% if can_create_message %}
  <a class="action text-sm"
     href="{% url 'private_messages:message_create' %}">{% trans "Send Message "%}</a>
  {% endif %}

</div>


{% endwith %}

{% block message_list %}{% endblock %}

{% endblock content %}

templates/private_messages/outbox.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/message_list_base.html" %}

{% load i18n %}

{% block subtitle %}{{ block.super }} / {% translate "Outbox" %}{% endblock %}

{% block message_list %}

{% if paginator.count or search %}
{% include "includes/forms/search_form.html" with selector=True %}
{% endif %}

{% translate "You have not sent any messages" as t_empty_message %}
{% include "private_messages/includes/message_list.html" with empty_message=t_empty_message %}
{% endblock message_list %}

templates/private_messages/thread.html
{# Copyright (c) 2019 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/base.html" %}

{% load i18n %}
{% load account %}
{% load rules %}
{% load private_messages_tags %}
{% load users_tags %}

{% block private_messages_subtitle %} | {% user_display user_obj %}{% endblock %}

{% block content %}
<h3>{% trans "Messages" %}</h3>
<h4>
    {% avatar user_obj "avatar-lg" %}
    <a href="{{ user_obj.get_absolute_url }}">{% user_display user_obj %}</a>
</h4>
<div class="actions" data-controller="toggle">
      {% get_unread_message_count user community as unread_messages %}
      <span {% if unread_messages %}class="badge" data-badge="{{ unread_messages }}"{% endif %}>
        <a href="{% url 'private_messages:inbox'%}">{% trans "Inbox" %}</a>
      </span>

    <a href="{% url 'private_messages:outbox' %}">{% trans "Outbox" %}</a>
    {% has_perm "private_messages.create_message" user community as can_create_message %}

    {% if can_create_message and user not in user_obj.blocked.all %}
    <a href="{% url 'private_messages:message_create' user_obj.username %}">{% trans "Send Message" %}</a>
    {% endif %}

</div>
<div class="divider"></div>

{% if paginator.count or view.search_query %}
{% include "includes/search_form.html" %}
{% endif %}

{% include "private_messages/includes/email_settings.html" %}

{% if object_list %}
{% for message in object_list %}
<div class="card mb-1 {% if message.sender == user %} bg-gray{% endif %}">
    <div class="card-header">
        <div class="card-title h6">
            <span class="timesince">
                {% blocktrans with created=message.created|timesince %}
                Sent {{ created }} ago by
                {% endblocktrans %}
                {% include "users/includes/chip.html" with profile=message.sender %}
                {% include "private_messages/includes/parent.html" %}
            </span>
        </div>
    </div>
    <div class="card-body">
        {% include "private_messages/includes/message.html" %}
    </div>
    <div class="card-footer">
        <div class="actions">
            <a href="{{ message.get_permalink }}">{% trans "Permalink" %}</a>
            {% if message.sender == request.user %}

            <a href="{% url 'private_messages:message_update' message.id %}">{% trans "Edit" %}</a>

            <a href="{% url 'private_messages:message_delete' message.id %}"
               data-controller="ajax confirm"
               data-action="confirm#check ajax#delete"
               data-ajax-redirect="{{ request.path }}"
               data-confirm-header="{% trans 'Delete' %}"
               data-confirm-body="{% trans 'Are you sure you want to delete this message?' %}"
               >{% trans "Delete" %}</a>

            {% elif not message.read %}
            <a href="{% url 'private_messages:message_mark_read' message.id %}"
               data-controller="ajax"
               data-action="ajax#post"
               data-ajax-redirect="{{ request.path }}"
               >{% trans "Mark As Read" %}</a>
            {% endif %}
            {% include "private_messages/includes/replies.html" %}
        </div>
    </div>
</div>
{% endfor %}
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}
{% endblock %}